"use client";

import { useState, useEffect, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

interface MockupPreviewProps {
  productId: number;
  designUrl: string;
  variantIds: number[];
}

interface MockupStyle {
  id: number;
  category_name: string;
  view_name: string;
  restricted_to_variants: number[] | null;
}

interface PlacementInfo {
  placement: string;
  display_name: string;
  technique: string;
  print_area_width: number;
  print_area_height: number;
  mockup_styles: MockupStyle[];
}

interface GeneratedMockup {
  placement: string;
  mockup_url: string;
  style_id?: number;
  display_name?: string;
  // Legacy fields
  extra?: Array<{ title: string; url: string }>;
  variant_ids?: number[];
}

export function MockupPreview({
  productId,
  designUrl,
  variantIds,
}: MockupPreviewProps) {
  const [placements, setPlacements] = useState<PlacementInfo[]>([]);
  const [selectedPlacement, setSelectedPlacement] = useState<string>("");
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const [selectedStyleIds, setSelectedStyleIds] = useState<number[]>([]);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [mockups, setMockups] = useState<GeneratedMockup[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [autoGenerated, setAutoGenerated] = useState(false);

  // Position state (inches for v2 API)
  const [designScale, setDesignScale] = useState(80); // % of print area

  // Load available styles and placements
  useEffect(() => {
    async function loadStyles() {
      setLoading(true);
      try {
        const res = await fetch(`/api/printful/mockups?productId=${productId}`);
        const data = await res.json();

        if (data.styles && Array.isArray(data.styles)) {
          setPlacements(data.styles);
          // Default to first placement (usually "front")
          if (data.styles.length > 0) {
            const frontPlacement = data.styles.find(
              (p: PlacementInfo) => p.placement === "front"
            );
            setSelectedPlacement(
              frontPlacement?.placement || data.styles[0].placement
            );
          }
        }
      } catch {
        setError("Failed to load mockup options");
      }
      setLoading(false);
    }
    loadStyles();
  }, [productId]);

  // Auto-generate mockup when design URL is set
  useEffect(() => {
    if (designUrl && selectedPlacement && !autoGenerated && placements.length > 0) {
      generateMockup();
      setAutoGenerated(true);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [designUrl, selectedPlacement, placements]);

  // Reset auto-gen flag when design changes
  useEffect(() => {
    setAutoGenerated(false);
    setMockups([]);
  }, [designUrl]);

  const currentPlacement = placements.find(
    (p) => p.placement === selectedPlacement
  );

  // Group styles by category
  const stylesByCategory: Record<string, MockupStyle[]> = {};
  if (currentPlacement) {
    for (const style of currentPlacement.mockup_styles) {
      const cat = style.category_name || "Default";
      if (!stylesByCategory[cat]) stylesByCategory[cat] = [];
      stylesByCategory[cat].push(style);
    }
  }

  const categories = Object.keys(stylesByCategory);

  const generateMockup = useCallback(async () => {
    if (!designUrl || !selectedPlacement) return;

    setGenerating(true);
    setError(null);

    try {
      const placement = placements.find(
        (p) => p.placement === selectedPlacement
      );
      if (!placement) {
        setError("Placement not found");
        setGenerating(false);
        return;
      }

      // Calculate position based on scale (centered)
      const areaW = placement.print_area_width;
      const areaH = placement.print_area_height;
      const scale = designScale / 100;
      const designW = areaW * scale;
      const designH = areaH * scale;
      const position = {
        width: parseFloat(designW.toFixed(2)),
        height: parseFloat(designH.toFixed(2)),
        top: parseFloat(((areaH - designH) / 2).toFixed(2)),
        left: parseFloat(((areaW - designW) / 2).toFixed(2)),
      };

      const res = await fetch("/api/printful/mockups", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          productId,
          variantIds: variantIds.slice(0, 5),
          designUrl,
          placement: selectedPlacement,
          technique: placement.technique || "dtg",
          position,
          styleIds: selectedStyleIds.length > 0 ? selectedStyleIds : undefined,
        }),
      });

      const taskData = await res.json();
      if (taskData.error) {
        setError(taskData.error);
        setGenerating(false);
        return;
      }

      // Poll for result — handle both v2 (id) and legacy (task_key) responses
      const taskId = taskData.id;
      const taskKey = taskData.task_key;
      let attempts = 0;

      const poll = async () => {
        attempts++;
        if (attempts > 30) {
          setError("Mockup generation timed out. Try again.");
          setGenerating(false);
          return;
        }

        const param = taskId
          ? `taskId=${taskId}`
          : `taskKey=${taskKey}`;
        const resultRes = await fetch(`/api/printful/mockups?${param}`);
        const result = await resultRes.json();

        // Handle v2 response
        if (Array.isArray(result) && result.length > 0) {
          const task = result[0];
          if (task.status === "completed" && task.catalog_variant_mockups) {
            const allMockups: GeneratedMockup[] = [];
            for (const vm of task.catalog_variant_mockups) {
              for (const m of vm.mockups || []) {
                // Deduplicate by URL
                if (!allMockups.find((existing) => existing.mockup_url === m.mockup_url)) {
                  allMockups.push({
                    placement: m.placement,
                    mockup_url: m.mockup_url,
                    style_id: m.style_id,
                    display_name: m.display_name,
                  });
                }
              }
            }
            setMockups(allMockups);
            setGenerating(false);
            return;
          }
          if (task.status === "failed") {
            setError(task.failure_reasons?.join(", ") || "Mockup generation failed");
            setGenerating(false);
            return;
          }
        }

        // Handle legacy response
        if (result.status === "completed" && result.mockups) {
          setMockups(result.mockups);
          setGenerating(false);
          return;
        }
        if (result.status === "failed") {
          setError(result.error || "Mockup generation failed");
          setGenerating(false);
          return;
        }

        setTimeout(poll, 2000);
      };

      setTimeout(poll, 3000);
    } catch {
      setError("Failed to generate mockup");
      setGenerating(false);
    }
  }, [
    designUrl,
    productId,
    variantIds,
    selectedPlacement,
    placements,
    designScale,
    selectedStyleIds,
  ]);

  if (loading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Mockup Preview</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground">Loading mockup options...</p>
        </CardContent>
      </Card>
    );
  }

  if (placements.length === 0) return null;

  return (
    <Card>
      <CardHeader>
        <CardTitle>Mockup Preview</CardTitle>
        <CardDescription>
          {designUrl
            ? "Preview your design on the product. Adjust placement and style below."
            : "Upload a design above to see mockup previews."}
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        {error && (
          <div className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">
            {error}
          </div>
        )}

        {/* Placement tabs */}
        {placements.length > 1 && (
          <div className="space-y-2">
            <Label className="text-sm font-medium">Print Placement</Label>
            <div className="flex flex-wrap gap-2">
              {placements.map((p) => (
                <button
                  key={p.placement}
                  type="button"
                  onClick={() => {
                    setSelectedPlacement(p.placement);
                    setSelectedCategory(null);
                    setSelectedStyleIds([]);
                  }}
                  className="focus:outline-none"
                >
                  <Badge
                    variant={
                      selectedPlacement === p.placement ? "default" : "outline"
                    }
                    className="cursor-pointer px-3 py-1"
                  >
                    {p.display_name}
                  </Badge>
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Style categories */}
        {categories.length > 0 && (
          <div className="space-y-2">
            <Label className="text-sm font-medium">Mockup Style</Label>
            <div className="flex flex-wrap gap-2">
              <button
                type="button"
                onClick={() => {
                  setSelectedCategory(null);
                  setSelectedStyleIds([]);
                }}
                className="focus:outline-none"
              >
                <Badge
                  variant={selectedCategory === null ? "default" : "outline"}
                  className="cursor-pointer px-3 py-1"
                >
                  All Styles
                </Badge>
              </button>
              {categories.map((cat) => (
                <button
                  key={cat}
                  type="button"
                  onClick={() => {
                    setSelectedCategory(cat);
                    setSelectedStyleIds(
                      stylesByCategory[cat].map((s) => s.id)
                    );
                  }}
                  className="focus:outline-none"
                >
                  <Badge
                    variant={selectedCategory === cat ? "default" : "outline"}
                    className="cursor-pointer px-3 py-1"
                  >
                    {cat} ({stylesByCategory[cat].length})
                  </Badge>
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Design scale slider */}
        {designUrl && (
          <div className="space-y-2">
            <Label className="text-sm font-medium">
              Design Size: {designScale}%
            </Label>
            <input
              type="range"
              min={20}
              max={100}
              value={designScale}
              onChange={(e) => setDesignScale(parseInt(e.target.value))}
              className="w-full accent-primary"
            />
            <div className="flex justify-between text-xs text-muted-foreground">
              <span>Small (20%)</span>
              <span>Full (100%)</span>
            </div>
          </div>
        )}

        {/* Generate button */}
        {designUrl && (
          <Button
            type="button"
            onClick={generateMockup}
            disabled={generating}
          >
            {generating
              ? "Generating mockups..."
              : mockups.length > 0
                ? "Regenerate Mockups"
                : "Generate Mockup Preview"}
          </Button>
        )}

        {/* Generated mockups grid */}
        {mockups.length > 0 && (
          <div className="space-y-3">
            <h4 className="text-sm font-medium">
              Generated Mockups ({mockups.length})
            </h4>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
              {mockups.map((mockup, i) => (
                <div key={i} className="space-y-1">
                  <img
                    src={mockup.mockup_url}
                    alt={mockup.display_name || `Mockup ${i + 1}`}
                    className="w-full rounded-md border aspect-square object-cover"
                  />
                  <p className="text-xs text-muted-foreground text-center">
                    {mockup.display_name || mockup.placement}
                  </p>
                  {/* Legacy extra views */}
                  {mockup.extra?.map((extra, j) => (
                    <div key={j}>
                      <img
                        src={extra.url}
                        alt={extra.title}
                        className="w-full rounded-md border aspect-square object-cover"
                      />
                      <p className="text-xs text-muted-foreground text-center">
                        {extra.title}
                      </p>
                    </div>
                  ))}
                </div>
              ))}
            </div>
          </div>
        )}

        {generating && (
          <div className="text-center py-8">
            <div className="inline-block h-6 w-6 animate-spin rounded-full border-2 border-primary border-t-transparent" />
            <p className="mt-2 text-sm text-muted-foreground">
              Generating mockups — this takes 5-15 seconds...
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
