-- EZMerch Initial Schema
-- Multi-tenant POD e-commerce platform

-- ============================================================
-- ENUMS
-- ============================================================

CREATE TYPE public.app_role AS ENUM ('admin', 'store_owner', 'customer');

CREATE TYPE public.shipping_policy AS ENUM ('passthrough', 'free', 'flat_discount');

-- ============================================================
-- TABLES
-- ============================================================

-- Stores (core tenant table)
CREATE TABLE public.stores (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  slug text UNIQUE NOT NULL,
  name text NOT NULL,
  owner_id uuid REFERENCES auth.users(id),
  stripe_account_id text,
  claim_token text UNIQUE,
  claim_token_expires_at timestamptz,
  claimed boolean DEFAULT false NOT NULL,
  brand_colors jsonb DEFAULT '{"primary": "#000000", "accent": "#3b82f6"}'::jsonb NOT NULL,
  logo_url text,
  shipping_policy public.shipping_policy DEFAULT 'passthrough' NOT NULL,
  shipping_discount_cents integer,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- Products (belong to a store)
CREATE TABLE public.products (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  store_id uuid REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
  printful_sync_product_id bigint,
  title text NOT NULL,
  description text,
  variants jsonb DEFAULT '[]'::jsonb NOT NULL,
  published boolean DEFAULT false NOT NULL,
  thumbnail_url text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- Orders
CREATE TABLE public.orders (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  store_id uuid REFERENCES public.stores(id) NOT NULL,
  customer_id uuid REFERENCES auth.users(id),
  customer_email text NOT NULL,
  stripe_payment_intent_id text UNIQUE,
  printful_order_id bigint,
  status text DEFAULT 'pending' NOT NULL
    CHECK (status IN ('pending', 'paid', 'fulfilling', 'fulfillment_failed', 'shipped', 'delivered', 'failed', 'refunded')),
  printful_error text,
  retry_count integer DEFAULT 0 NOT NULL,
  subtotal_cents integer NOT NULL,
  shipping_cents integer DEFAULT 0 NOT NULL,
  tax_cents integer DEFAULT 0 NOT NULL,
  total_cents integer NOT NULL,
  platform_fee_cents integer DEFAULT 0 NOT NULL,
  shipping_address jsonb NOT NULL,
  tracking_number text,
  tracking_url text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- Order items
CREATE TABLE public.order_items (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  order_id uuid REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
  product_id uuid REFERENCES public.products(id) NOT NULL,
  variant_key text NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  price_cents integer NOT NULL CHECK (price_cents > 0)
);

-- Profiles
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  display_name text,
  avatar_url text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- User roles
CREATE TABLE public.user_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role public.app_role NOT NULL,
  store_id uuid REFERENCES public.stores(id) ON DELETE CASCADE,
  UNIQUE (user_id, role, store_id)
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_stores_owner_id ON public.stores(owner_id);
CREATE INDEX idx_stores_slug ON public.stores(slug);
CREATE INDEX idx_stores_claim_token ON public.stores(claim_token) WHERE claim_token IS NOT NULL;
CREATE INDEX idx_products_store_id ON public.products(store_id);
CREATE INDEX idx_products_published ON public.products(store_id, published) WHERE published = true;
CREATE INDEX idx_orders_store_id ON public.orders(store_id);
CREATE INDEX idx_orders_customer_id ON public.orders(customer_id) WHERE customer_id IS NOT NULL;
CREATE INDEX idx_orders_status ON public.orders(status);
CREATE INDEX idx_orders_stripe_pi ON public.orders(stripe_payment_intent_id) WHERE stripe_payment_intent_id IS NOT NULL;
CREATE INDEX idx_order_items_order_id ON public.order_items(order_id);
CREATE INDEX idx_user_roles_user_id ON public.user_roles(user_id);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- STORES policies
CREATE POLICY "Anyone can view stores"
  ON public.stores FOR SELECT
  USING (true);

CREATE POLICY "Admins can manage all stores"
  ON public.stores FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Owners can update their store"
  ON public.stores FOR UPDATE
  USING (auth.uid() = owner_id);

-- PRODUCTS policies
CREATE POLICY "Anyone can view published products"
  ON public.products FOR SELECT
  USING (published = true);

CREATE POLICY "Admins can manage all products"
  ON public.products FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Store owners can manage their products"
  ON public.products FOR ALL
  USING (
    store_id IN (
      SELECT id FROM public.stores WHERE owner_id = auth.uid()
    )
  );

-- ORDERS policies
CREATE POLICY "Customers can view own orders"
  ON public.orders FOR SELECT
  USING (customer_id = auth.uid());

CREATE POLICY "Store owners can view their store orders"
  ON public.orders FOR SELECT
  USING (
    store_id IN (
      SELECT id FROM public.stores WHERE owner_id = auth.uid()
    )
  );

CREATE POLICY "Admins can manage all orders"
  ON public.orders FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid() AND role = 'admin'
    )
  );

-- ORDER ITEMS policies
CREATE POLICY "Anyone can view order items for their orders"
  ON public.order_items FOR SELECT
  USING (
    order_id IN (
      SELECT id FROM public.orders
      WHERE customer_id = auth.uid()
         OR store_id IN (SELECT id FROM public.stores WHERE owner_id = auth.uid())
    )
  );

CREATE POLICY "Admins can manage all order items"
  ON public.order_items FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid() AND role = 'admin'
    )
  );

-- PROFILES policies
CREATE POLICY "Users can view own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

-- USER ROLES policies
CREATE POLICY "Users can view own roles"
  ON public.user_roles FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "Admins can manage all roles"
  ON public.user_roles FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid() AND role = 'admin'
    )
  );

-- ============================================================
-- FUNCTIONS
-- ============================================================

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (new.id, new.raw_user_meta_data ->> 'display_name');

  -- Default role: customer
  INSERT INTO public.user_roles (user_id, role)
  VALUES (new.id, 'customer');

  RETURN new;
END;
$$;

-- Trigger on auth.users insert
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER set_stores_updated_at
  BEFORE UPDATE ON public.stores
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_products_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_orders_updated_at
  BEFORE UPDATE ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- Atomic store claim function
CREATE OR REPLACE FUNCTION public.claim_store(p_token text, p_user_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_store_id uuid;
BEGIN
  -- Find unclaimed store with valid, non-expired token
  SELECT id INTO v_store_id
  FROM public.stores
  WHERE claim_token = p_token
    AND claimed = false
    AND (claim_token_expires_at IS NULL OR claim_token_expires_at > now())
  FOR UPDATE;

  IF v_store_id IS NULL THEN
    RAISE EXCEPTION 'Invalid or expired claim token';
  END IF;

  -- Bind store to user
  UPDATE public.stores
  SET owner_id = p_user_id,
      claimed = true,
      claim_token = NULL,
      claim_token_expires_at = NULL,
      updated_at = now()
  WHERE id = v_store_id;

  -- Add store_owner role
  INSERT INTO public.user_roles (user_id, role, store_id)
  VALUES (p_user_id, 'store_owner', v_store_id)
  ON CONFLICT (user_id, role, store_id) DO NOTHING;

  RETURN v_store_id;
END;
$$;
